### ISSUE TITLE
Highlight contrast

### ISSUE THREAD

**Issue by druellan** [LeGfrey/rocket-ui#1]
Love this!
But the contrast of the highlight color can be improved a bit, seems too light for some colors?

![2017-09-04_20h54_13](https://user-images.githubusercontent.com/6965667/30040287-9b04dbc4-91b3-11e7-9c07-0abbb6887e75.png)

**Comment by g3offrey** [comment]
Hi ✌️

Hope your having a good day.
Thank you for your feedback. 😄

I agree, I'll adjust this color, and ship it with the next version.

For information I updated a bit the repository adding some CI to ship modification faster so resolving the contrast is my next TODO.

**Comment by g3offrey** [comment]
I made a test, what do you think about that ? Is it still too light ? 😅 
![screenshot contrast](https://user-images.githubusercontent.com/11151445/30172069-04f599f0-93f4-11e7-80aa-6daa11e29a8b.png)

**Comment by druellan** [comment]
Oh, I think it looks better now!

**Comment by g3offrey** [comment]
Ok nice I'm releasing a new version containing this fix and and normalization of colors for list and autocomplete.

I close the issue, as the new version will be available in a couple of minutes. 😄
