### ISSUE TITLE
Add Italic Support for Additional Keywords Using Operator Mono font

### ISSUE THREAD

**Issue by Jaballadares** [LeGfrey/rocket-ui#2]
Hi there, thanks for such a great theme! By far my favorite I've ever used. This isn't an issue, but more of a "like-to-have". Forgive me if I am not using the Github issues the right way, I'm still new to the whole open source world. 

I was hoping you could help me add the italic font style for a particular type of keyword. The chester theme has these words italicized and so do some of the themes in sublime text when using operator mono. 

Thanks in advance!

Current appearance:
<img width="720" alt="default styling" src="https://user-images.githubusercontent.com/4951251/30628544-d6bfbdd0-9d8b-11e7-940f-f6b5da6d5f9c.png">

Desired appearance: 
<img width="566" alt="italic_for_mtk5" src="https://user-images.githubusercontent.com/4951251/30628510-a348c384-9d8b-11e7-8f10-819dec14a867.png">

**Comment by Jaballadares** [comment]
Actually, I figured it out by just adding the style in the themes json file. Sorry about that!

**Comment by g3offrey** [comment]
HI @Jaballadares,
thanks for taking time to create an issue and helping me 👍 

Oh you mean you want xml attribute in italic ? 
I can do this ! This is a better in my opinion, so you are right 😄 

I'll add this for the next version (0.11) this weekend.

Thank you 😄

**Comment by Jaballadares** [comment]
@LeGfrey you're the man! 

Thank you.

**Comment by g3offrey** [comment]
Merged inside #3. Let me know if you have more feedbacks.
Hadn't so much free time to add more features (additional accent colors for example) in this version, but will do soon 😅
